<?php

namespace OpenFlexImporter;

class OpenFlexClient {
    private $token;

    const VEHICLES_EXAMPLE = <<<EOD
{
    "total": 2,
    "items": [
        {
            "id": 199,
            "entityId": 41,
            "pointOfSale": {
                "id": 54,
                "name": "Point de vente 2 (François D.)",
                "zipCode": "69003",
                "city": "Lyon",
                "latitude": null,
                "longitude": null
            },
            "physicalPresencePointOfSale": {
                "id": 53,
                "name": "Point de vente 1 (François D.)",
                "zipCode": "71100",
                "city": "Chalon-sur-Saône",
                "latitude": null,
                "longitude": null
            },
            "physicalPresenceSite": null,
            "configuration": 3,
            "destination": 1,
            "referential": 1,
            "referentialCarId": "82825",
            "typeId": "10",
            "type": "Véhicule particulier",
            "makeId": "16",
            "make": "JAGUAR",
            "modelGroupId": "2365",
            "modelGroup": "X-TYPE",
            "generation": "X-TYPE",
            "modelId": "2365",
            "model": "X-TYPE",
            "trim": "Classique",
            "version": "X-Type 2.0i V6",
            "fuelId": "00100001",
            "fuel": "Essence sans plomb",
            "genericFuelId": 1,
            "genericFuel": "Essence",
            "transmissionTypeId": "00180001",
            "transmissionType": "Boîte manuelle",
            "genericTransmissionTypeId": 1,
            "genericTransmissionType": "Boîte manuelle",
            "bodyId": "00010060",
            "body": "Berline",
            "genericBodyId": 11,
            "genericBody": "Berline",
            "segmentationId": "00030005",
            "segmentation": "Moyenne supérieure",
            "driveTypeId": "00050001",
            "driveType": "Traction avant",
            "genericDriveTypeId": 1,
            "genericDriveType": "2 roues motrices",
            "emissionId": "00170007",
            "emission": "G-Kat",
            "seats": 5,
            "gears": 5,
            "doors": 4,
            "valves": 4,
            "torque": 196,
            "displacement": 2099,
            "cylinders": 6,
            "cylindersTypeId": "00080002",
            "cylindersType": "V",
            "horsepower": 159,
            "taxHorsepower": 10,
            "kilowatt": 117,
            "co2Emission": 219,
            "wltpCo2EmissionMin": null,
            "wltpCo2EmissionMax": null,
            "realCo2Emission": 219,
            "mixedConsumption": 9.2,
            "urbanConsumption": 12.7,
            "extraUrbanConsumption": 7.1,
            "length": 4672,
            "width": 2003,
            "height": 1392,
            "totalWeight": 2025,
            "payload": 575,
            "wheelbase": null,
            "trailerLoadBraked": null,
            "trailerLoadUnbraked": null,
            "roofload": 75,
            "energeticEfficiency": null,
            "curbWeight": 1450,
            "realCurbWeight": null,
            "topSpeed": 210,
            "acceleration": 9.4,
            "trunkMinimumCapacity": 452,
            "trunkMaximumCapacity": 0,
            "modelCatalogBegin": "2002-02-01T01:00:00+01:00",
            "modelCatalogEnd": "2005-08-01T02:00:00+02:00",
            "catalogBeginPrice": "2002-02-01T01:00:00+01:00",
            "catalogEndPrice": "2003-08-31T02:00:00+02:00",
            "catalogExclVatPrice": 28595.32,
            "catalogInclVatPrice": 34200,
            "catalogTax": 19.6,
            "catalogPriceOverloaded": false,
            "frontTyreWidth": "205",
            "frontTyreHeight": "55",
            "frontTyreSpeedIndex": "R",
            "frontTyreDiameter": "16",
            "rearTyreWidth": "205",
            "rearTyreHeight": "55",
            "rearTyreSpeedIndex": "R",
            "rearTyreDiameter": "16",
            "internalColorCode": null,
            "internalColorWording": "Noir",
            "internalColorReference": "000000",
            "externalColorCode": null,
            "externalColorWording": "Bleu",
            "externalColorReference": "007cad",
            "putIntoService": "2002-03-19T01:00:00+01:00",
            "mileage": 128597,
            "mileageDate": "2021-06-05T01:04:33+02:00",
            "guaranteedMileage": true,
            "numberplate": "DC789AT",
            "chassis": "SAJAA53S22YC32220",
            "registration": "2019-12-04T01:00:00+01:00",
            "registrationNumber": null,
            "codeFactory": null,
            "recoverableVat": 2,
            "tcenum": "MDA17x2Hxxxx",
            "cultureId": null,
            "referentialPicture": "https://filerender-api.openflex-preprod.eu/files/images/CvgF3D6OQwoCk%2Btflg2aX3Zf4mzC1n7YqV2Pteut6zd6nWb_DFXWZWcSeoPfUCXXnczP06IA8eLnHuFddcEad89rgETGkwGiog%3D%3D",
            "picture": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOOa3jvRZ/JAGUAR_X-TYPE_34_AVANT_GAUCHE.jpg",
            "damaged": false,
            "firstHand": false,
            "rolling": true,
            "upToDateMaintenanceBook": true,
            "purchaseSource": "Reprise sur VN",
            "origin": 1,
            "import": false,
            "importCountryIso": null,
            "depositSale": false,
            "previousOwner": "TOTO",
            "sellerBuyer": "François DE MONSABERT",
            "forecastedMileage": null,
            "forecastedDate": null,
            "referenced": true,
            "stockEntrance": "2021-06-05T01:04:39+02:00",
            "internalNumber": "VOJAG6545",
            "standingTimeAlert": false,
            "automaticPriceUpdate": false,
            "isExported": false,
            "technicalControl": "2021-06-04T01:05:49+02:00",
            "nextTechnicalControl": null,
            "status": {
                "code": "SAST",
                "wording": "Stock de vente"
            },
            "deliveryDate": null,
            "ordered": null,
            "warranty": "VO24",
            "warrantyDuration": null,
            "warrantyEnd": "2021-10-29T18:52:09+02:00",
            "assignment": null,
            "collaboratorAssignmentId": null,
            "reconciliationStatus": null,
            "price": 9500,
            "referentialPollutionClassification": null,
            "pollutionClassificationDesignation": null,
            "pollutionClassificationValue": null,
            "pollutionClassificationMedia": null,
            "comment": "commentaire test VO",
            "eReserved": false,
            "updatedAt": "2023-05-04T17:01:17+02:00",
            "powertrainId": null,
            "powertrain": null,
            "numberOfBatteries": null,
            "batteryTypeId": null,
            "batteryType": null,
            "batteryCapacityAh": null,
            "batteryCapacityKwh": null,
            "homeBatteryChargingTime": null,
            "fastBatteryChargingTime": null,
            "hybridizationTypeId": null,
            "hybridizationType": null,
            "autonomy": null,
            "gasTypeId": null,
            "gasType": null,
            "electricConsumption": null,
            "gasTankCapacity": null,
            "gasTankCapacityUnit": null,
            "gasUrbanConsumption": null,
            "gasExtraUrbanConsumption": null,
            "gasMixedConsumption": null,
            "gasConsumptionUnit": null,
            "federalMotorTransportAuthorityNumber": null,
            "previousOwnerCustomer": null,
            "insurancePremiumIndex": null,
            "trailerHitch": null,
            "trailerHitchValue": null,
            "bonusPrice": null,
            "penaltyPrice": null,
            "privateExclVatPrice": 9500,
            "privateInclVatPrice": 9500,
            "professionalExclVatPrice": null,
            "professionalInclVatPrice": null,
            "equipmentsPrice": 2280,
            "saddleriesPrice": 0,
            "paintingsPrice": 0,
            "serviceAgreementsPrice": 960,
            "damagesRepaired": null
        },
        {
            "id": 45,
            "entityId": 41,
            "pointOfSale": {
                "id": 53,
                "name": "Point de vente 1 (François D.)",
                "zipCode": "71100",
                "city": "Chalon-sur-Saône",
                "latitude": null,
                "longitude": null
            },
            "physicalPresencePointOfSale": {
                "id": 53,
                "name": "Point de vente 1 (François D.)",
                "zipCode": "71100",
                "city": "Chalon-sur-Saône",
                "latitude": null,
                "longitude": null
            },
            "physicalPresenceSite": null,
            "configuration": 3,
            "destination": 2,
            "referential": 1,
            "referentialCarId": "204897",
            "typeId": "20",
            "type": "Véhicule tout terrain",
            "makeId": "21",
            "make": "MERCEDES",
            "modelGroupId": "5680",
            "modelGroup": "CLASSE GLA",
            "generation": null,
            "modelId": "6553",
            "model": "GLA",
            "trim": "Inspiration",
            "version": "GLA 200",
            "fuelId": "00100001",
            "fuel": "Essence sans plomb",
            "genericFuelId": 1,
            "genericFuel": "Essence",
            "transmissionTypeId": "00180001",
            "transmissionType": "Boîte manuelle",
            "genericTransmissionTypeId": 1,
            "genericTransmissionType": "Boîte manuelle",
            "bodyId": "00010095",
            "body": "Tout-Terrain",
            "genericBodyId": 2,
            "genericBody": "SUV",
            "segmentationId": "00030050",
            "segmentation": "SUV légers",
            "driveTypeId": "00050001",
            "driveType": "Traction avant",
            "genericDriveTypeId": 1,
            "genericDriveType": "2 roues motrices",
            "emissionId": "00170007",
            "emission": "G-Kat",
            "seats": 5,
            "gears": 6,
            "doors": 5,
            "valves": 4,
            "torque": 250,
            "displacement": 1595,
            "cylinders": 4,
            "cylindersTypeId": "00080001",
            "cylindersType": "Ligne",
            "horsepower": 156,
            "taxHorsepower": 9,
            "kilowatt": 115,
            "co2Emission": 141,
            "wltpCo2EmissionMin": null,
            "wltpCo2EmissionMax": null,
            "realCo2Emission": 141,
            "mixedConsumption": 6.6,
            "urbanConsumption": 0,
            "extraUrbanConsumption": 0,
            "length": 4424,
            "width": 1804,
            "height": 1494,
            "totalWeight": 1940,
            "payload": 545,
            "wheelbase": null,
            "trailerLoadBraked": null,
            "trailerLoadUnbraked": null,
            "roofload": 0,
            "energeticEfficiency": null,
            "curbWeight": 1395,
            "realCurbWeight": null,
            "topSpeed": 215,
            "acceleration": 8.4,
            "trunkMinimumCapacity": 421,
            "trunkMaximumCapacity": 0,
            "modelCatalogBegin": "2018-05-01T02:00:00+02:00",
            "modelCatalogEnd": "2020-03-01T01:00:00+01:00",
            "catalogBeginPrice": "2019-09-03T02:00:00+02:00",
            "catalogEndPrice": "2020-03-31T02:00:00+02:00",
            "catalogExclVatPrice": 29416.67,
            "catalogInclVatPrice": 35300,
            "catalogTax": 20,
            "catalogPriceOverloaded": false,
            "frontTyreWidth": "215",
            "frontTyreHeight": "60",
            "frontTyreSpeedIndex": "R",
            "frontTyreDiameter": "17",
            "rearTyreWidth": "215",
            "rearTyreHeight": "60",
            "rearTyreSpeedIndex": "R",
            "rearTyreDiameter": "17",
            "internalColorCode": null,
            "internalColorWording": "Noir",
            "internalColorReference": "000000",
            "externalColorCode": null,
            "externalColorWording": "Blanc",
            "externalColorReference": "ffffff",
            "putIntoService": "2021-09-23T02:00:00+02:00",
            "mileage": 19527,
            "mileageDate": null,
            "guaranteedMileage": false,
            "numberplate": "FK589NV",
            "chassis": "WDC1569431J661747",
            "registration": null,
            "registrationNumber": null,
            "codeFactory": "156943_FR1",
            "recoverableVat": 2,
            "tcenum": "n.c.",
            "cultureId": null,
            "referentialPicture": "https://filerender-api.openflex-preprod.eu/files/images/plsQ_2MLjse40wQUWvUZRBz3_W4HkPNYga+GmO7DlbuIOR0gr+fgic2wAQISUy6KNKp0EYR_MjJnCfMBmq9rgTWbZecI_fYSzg==",
            "picture": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxODF6UjVfYJLXpgw%3D%3D/MERCEDES_GLA_FACE_AVANT.jpg",
            "damaged": false,
            "firstHand": true,
            "rolling": true,
            "upToDateMaintenanceBook": false,
            "purchaseSource": null,
            "origin": 1,
            "import": false,
            "importCountryIso": null,
            "depositSale": false,
            "previousOwner": null,
            "sellerBuyer": null,
            "forecastedMileage": 19527,
            "forecastedDate": null,
            "referenced": true,
            "stockEntrance": "2021-09-01T00:00:00+02:00",
            "internalNumber": "VOMER123",
            "standingTimeAlert": false,
            "automaticPriceUpdate": false,
            "isExported": false,
            "technicalControl": null,
            "nextTechnicalControl": null,
            "status": {
                "code": "SAST",
                "wording": "Stock de vente"
            },
            "deliveryDate": null,
            "ordered": null,
            "warranty": "VO24",
            "warrantyDuration": 24,
            "warrantyEnd": null,
            "assignment": null,
            "collaboratorAssignmentId": null,
            "reconciliationStatus": null,
            "price": 26987.2,
            "referentialPollutionClassification": null,
            "pollutionClassificationDesignation": null,
            "pollutionClassificationValue": null,
            "pollutionClassificationMedia": null,
            "comment": null,
            "eReserved": false,
            "updatedAt": "2023-05-04T17:01:17+02:00",
            "powertrainId": null,
            "powertrain": null,
            "numberOfBatteries": null,
            "batteryTypeId": null,
            "batteryType": null,
            "batteryCapacityAh": null,
            "batteryCapacityKwh": null,
            "homeBatteryChargingTime": null,
            "fastBatteryChargingTime": null,
            "hybridizationTypeId": null,
            "hybridizationType": null,
            "autonomy": null,
            "gasTypeId": null,
            "gasType": null,
            "electricConsumption": null,
            "gasTankCapacity": null,
            "gasTankCapacityUnit": null,
            "gasUrbanConsumption": null,
            "gasExtraUrbanConsumption": null,
            "gasMixedConsumption": null,
            "gasConsumptionUnit": null,
            "federalMotorTransportAuthorityNumber": null,
            "previousOwnerCustomer": null,
            "insurancePremiumIndex": null,
            "trailerHitch": null,
            "trailerHitchValue": null,
            "bonusPrice": null,
            "penaltyPrice": null,
            "privateExclVatPrice": 27790.7,
            "privateInclVatPrice": 27790.7,
            "professionalExclVatPrice": 26987.2,
            "professionalInclVatPrice": 26987.2,
            "equipmentsPrice": 850,
            "saddleriesPrice": 0,
            "paintingsPrice": 0,
            "serviceAgreementsPrice": 0,
            "damagesRepaired": false
        }
    ]
}
EOD;

    const VEHICLE_DETAILS_EXAMPLE = <<<EOD
    {
    "car": {
        "id": 199,
        "entityId": 41,
        "pointOfSale": {
            "id": 54,
            "name": "Point de vente 2 (François D.)",
            "zipCode": "69003",
            "city": "Lyon",
            "longitude": null,
            "latitude": null
        },
        "physicalPresencePointOfSale": {
            "id": 53,
            "name": "Point de vente 1 (François D.)",
            "zipCode": "71100",
            "city": "Chalon-sur-Saône",
            "longitude": null,
            "latitude": null
        },
        "physicalPresenceSite": null,
        "publicationContact": null,
        "configuration": 3,
        "destination": 1,
        "referential": 1,
        "referentialCarId": "82825",
        "typeId": "10",
        "type": "Véhicule particulier",
        "makeId": "16",
        "make": "JAGUAR",
        "modelGroupId": "2365",
        "modelGroup": "X-TYPE",
        "generation": "X-TYPE",
        "modelId": "2365",
        "model": "X-TYPE",
        "trim": "Classique",
        "version": "X-Type 2.0i V6",
        "fuelId": "00100001",
        "fuel": "Essence sans plomb",
        "genericFuelId": 1,
        "genericFuel": "Essence",
        "transmissionTypeId": "00180001",
        "transmissionType": "Boîte manuelle",
        "genericTransmissionTypeId": 1,
        "genericTransmissionType": "Boîte manuelle",
        "bodyId": "00010060",
        "body": "Berline",
        "genericBodyId": 11,
        "genericBody": "Berline",
        "segmentationId": "00030005",
        "segmentation": "Moyenne supérieure",
        "driveTypeId": "00050001",
        "driveType": "Traction avant",
        "genericDriveTypeId": 1,
        "genericDriveType": "2 roues motrices",
        "emissionId": "00170007",
        "emission": "G-Kat",
        "seats": 5,
        "gears": 5,
        "doors": 4,
        "valves": 4,
        "torque": 196,
        "displacement": 2099,
        "cylinders": 6,
        "cylindersTypeId": "00080002",
        "cylindersType": "V",
        "horsepower": 159,
        "taxHorsepower": 10,
        "kilowatt": 117,
        "co2Emission": 219,
        "wltpCo2EmissionMin": null,
        "wltpCo2EmissionMax": null,
        "realCo2Emission": 219,
        "mixedConsumption": 9.2,
        "urbanConsumption": 12.7,
        "extraUrbanConsumption": 7.1,
        "length": 4672,
        "width": 2003,
        "height": 1392,
        "totalWeight": 2025,
        "payload": 575,
        "wheelbase": null,
        "trailerLoadBraked": null,
        "trailerLoadUnbraked": null,
        "roofload": 75,
        "energeticEfficiency": null,
        "curbWeight": 1450,
        "realCurbWeight": null,
        "topSpeed": 210,
        "acceleration": 9.4,
        "trunkMinimumCapacity": 452,
        "trunkMaximumCapacity": 0,
        "modelCatalogBegin": "2002-02-01T01:00:00+01:00",
        "modelCatalogEnd": "2005-08-01T02:00:00+02:00",
        "catalogBeginPrice": "2002-02-01T01:00:00+01:00",
        "catalogEndPrice": "2003-08-31T02:00:00+02:00",
        "catalogExclVatPrice": 28595.32,
        "catalogInclVatPrice": 34200,
        "catalogTax": 19.6,
        "catalogPriceOverloaded": false,
        "frontTyreWidth": "205",
        "frontTyreHeight": "55",
        "frontTyreSpeedIndex": "R",
        "frontTyreDiameter": "16",
        "rearTyreWidth": "205",
        "rearTyreHeight": "55",
        "rearTyreSpeedIndex": "R",
        "rearTyreDiameter": "16",
        "internalColorCode": null,
        "internalColorWording": "Noir",
        "internalColorReference": "000000",
        "externalColorCode": null,
        "externalColorWording": "Bleu",
        "externalColorReference": "007cad",
        "putIntoService": "2002-03-19T01:00:00+01:00",
        "mileage": 128597,
        "mileageDate": "2021-06-05T01:04:33+02:00",
        "guaranteedMileage": true,
        "numberplate": "DC789AT",
        "chassis": "SAJAA53S22YC32220",
        "registration": "2019-12-04T01:00:00+01:00",
        "registrationNumber": null,
        "codeFactory": null,
        "recoverableVat": 2,
        "tcenum": "MDA17x2Hxxxx",
        "cultureId": null,
        "referentialPicture": "https://filerender-api.openflex-preprod.eu/files/images/CvgF3D6OQwoCk%2Btflg2aX3Zf4mzC1n7YqV2Pteut6zd6nWb_DFXWZWcSeoPfUCXXnczP06IA8eLnHuFddcEad89rgETGkwGiog%3D%3D",
        "picture": null,
        "damaged": false,
        "firstHand": false,
        "rolling": true,
        "upToDateMaintenanceBook": true,
        "purchaseSource": null,
        "origin": 1,
        "originValue": "Particulier",
        "import": false,
        "importCountryIso": null,
        "depositSale": false,
        "sellerBuyer": "François DE MONSABERT",
        "forecastedMileage": null,
        "forecastedDate": null,
        "referenced": true,
        "stockEntrance": "2021-06-05T01:04:39+02:00",
        "internalNumber": "VOJAG6545",
        "standingTimeAlert": false,
        "automaticPriceUpdate": false,
        "isExported": false,
        "technicalControl": "2021-06-04T01:05:49+02:00",
        "nextTechnicalControl": null,
        "deliveryDate": null,
        "ordered": null,
        "warranty": "VO24",
        "warrantyDuration": null,
        "warrantyEnd": "2021-10-29T18:52:09+02:00",
        "assignment": null,
        "collaboratorAssignmentId": null,
        "reconciliationStatus": null,
        "price": 9500,
        "privateExclVatPrice": 9500,
        "privateInclVatPrice": 9500,
        "professionalExclVatPrice": null,
        "professionalInclVatPrice": null,
        "equipments": [
            {
                "id": 11725,
                "wording": "Pack vision",
                "code": null,
                "exclVatPrice": 1000,
                "inclVatPrice": 1200,
                "tax": 20,
                "referentialId": null,
                "serial": false,
                "pack": true,
                "custom": true,
                "packElements": [
                    {
                        "id": 1668,
                        "wording": "Feux LED AV/AR",
                        "code": "",
                        "updatedAt": "2021-06-04T15:38:34+02:00"
                    },
                    {
                        "id": 1669,
                        "wording": "Caméra infrarouge à vision nocturne",
                        "code": "",
                        "updatedAt": "2021-06-04T15:38:34+02:00"
                    }
                ],
                "equipmentGroupings": [],
                "updatedAt": "2023-05-04T15:31:15+02:00"
            },
            {
                "id": 11722,
                "wording": "Pack smoking",
                "code": "",
                "exclVatPrice": 400,
                "inclVatPrice": 480,
                "tax": 20,
                "referentialId": "179d71e2b9d",
                "serial": false,
                "pack": true,
                "custom": true,
                "packElements": [
                    {
                        "id": 1665,
                        "wording": "Allume cigare",
                        "code": "",
                        "updatedAt": "2021-06-04T15:04:05+02:00"
                    },
                    {
                        "id": 1666,
                        "wording": "Cendrier",
                        "code": "",
                        "updatedAt": "2021-06-04T15:04:05+02:00"
                    },
                    {
                        "id": 1667,
                        "wording": "Parfumeur d'ambiance",
                        "code": "",
                        "updatedAt": "2021-06-04T15:04:05+02:00"
                    }
                ],
                "equipmentGroupings": [],
                "updatedAt": "2023-05-04T15:31:15+02:00"
            },
            {
                "id": 11723,
                "wording": "Toit ouvrant panoramique",
                "code": "ABCDEF",
                "exclVatPrice": 500,
                "inclVatPrice": 600,
                "tax": 20,
                "referentialId": "179d71ebcc1",
                "serial": false,
                "pack": false,
                "custom": true,
                "packElements": [],
                "equipmentGroupings": [],
                "updatedAt": "2023-05-04T15:31:15+02:00"
            },
            {
                "id": 11724,
                "wording": "Barres de toit",
                "code": "BDT",
                "exclVatPrice": null,
                "inclVatPrice": null,
                "tax": null,
                "referentialId": "179d71f168d",
                "serial": true,
                "pack": false,
                "custom": true,
                "packElements": [],
                "equipmentGroupings": [],
                "updatedAt": "2021-06-04T15:04:05+02:00"
            }
        ],
        "pictures": [
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOOa3jvRZ/JAGUAR_X-TYPE_34_AVANT_GAUCHE.jpg",
                "templateReferenceId": 1
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOOe3jvRZ/JAGUAR_X-TYPE_PROFIL_GAUCHE.jpg",
                "templateReferenceId": 2
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOe%2B3jvRZ/JAGUAR_X-TYPE_34_ARRIERE_DROIT.jpg",
                "templateReferenceId": 5
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOe63jvRZ/JAGUAR_X-TYPE_PROFIL_DROIT.jpg",
                "templateReferenceId": 6
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOey3jvRZ/JAGUAR_X-TYPE_34_AVANT_DROIT.jpg",
                "templateReferenceId": 7
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs98gD2JbQHK96dG9SmHiDXFF_BuwkxMDF6VjVncOe23jvRZ/JAGUAR_X-TYPE_JANTE.jpg",
                "templateReferenceId": 9
            }
        ],
        "paintings": [
            {
                "id": 192,
                "wording": "Peinture de série",
                "code": null,
                "exclVatPrice": 0,
                "inclVatPrice": 0,
                "tax": null,
                "referentialId": " ",
                "serial": true,
                "custom": false,
                "updatedAt": "2023-05-04T15:31:15+02:00"
            }
        ],
        "saddleries": [
            {
                "id": 225,
                "wording": "Sellerie de série",
                "code": null,
                "exclVatPrice": 0,
                "inclVatPrice": 0,
                "tax": null,
                "referentialId": " ",
                "leather": false,
                "serial": true,
                "custom": false,
                "updatedAt": "2023-05-04T15:31:15+02:00"
            }
        ],
        "serviceAgreements": [
            {
                "id": 82,
                "wording": "ENTRETIEN 24",
                "code": "",
                "exclVatPrice": 800,
                "inclVatPrice": 960,
                "tax": 20,
                "referentialId": "179d71f9989",
                "serial": false,
                "custom": true,
                "updatedAt": "2023-05-04T15:31:15+02:00"
            }
        ],
        "deliveryPack": null,
        "accessories": [],
        "services": [],
        "status": {
            "id": "347",
            "code": "SAST",
            "wording": "Stock de vente"
        },
        "referentialPollutionClassification": null,
        "pollutionClassificationDesignation": null,
        "pollutionClassificationValue": null,
        "pollutionClassificationMedia": null,
        "comment": null,
        "eReserved": false,
        "updatedAt": "2023-05-04T15:31:15+02:00",
        "powertrainId": null,
        "powertrain": null,
        "numberOfBatteries": null,
        "batteryTypeId": null,
        "batteryType": null,
        "batteryCapacityAh": null,
        "batteryCapacityKwh": null,
        "homeBatteryChargingTime": null,
        "fastBatteryChargingTime": null,
        "hybridizationTypeId": null,
        "hybridizationType": null,
        "autonomy": null,
        "gasTypeId": null,
        "gasType": null,
        "electricConsumption": null,
        "gasTankCapacity": null,
        "gasTankCapacityUnit": null,
        "gasUrbanConsumption": null,
        "gasExtraUrbanConsumption": null,
        "gasMixedConsumption": null,
        "gasConsumptionUnit": null,
        "federalMotorTransportAuthorityNumber": null,
        "insurancePremiumIndex": null,
        "trailerHitch": null,
        "trailerHitchValue": null,
        "bonusPrice": null,
        "penaltyPrice": null,
        "equipmentsPrice": 2280,
        "saddleriesPrice": 0,
        "paintingsPrice": 0,
        "serviceAgreementsPrice": 960,
        "damagesRepaired": null
    }
}
EOD;

    const MOTORBIKE_DETAILS_EXAMPLE = <<<EOD
    {
    "car": {
        "id": 16,
        "entityId": 414,
        "pointOfSale": {
            "id": 622,
            "name": "Point de vente 1 (Vincent S.)",
            "zipCode": "71100",
            "city": "Chalon-sur-Saône",
            "longitude": 4.8437982,
            "latitude": 46.788839
        },
        "physicalPresencePointOfSale": {
            "id": 622,
            "name": "Point de vente 1 (Vincent S.)",
            "zipCode": "71100",
            "city": "Chalon-sur-Saône",
            "longitude": 4.8437982,
            "latitude": 46.788839
        },
        "physicalPresenceSite": null,
        "publicationContact": null,
        "configuration": 3,
        "destination": 1,
        "referential": 10,
        "referentialCarId": "190891",
        "typeId": "MTT2",
        "type": "MTT2",
        "genericTypeId": 2,
        "genericType": "MTT2",
        "makeId": "KAWASAKI",
        "make": "KAWASAKI",
        "modelGroupId": "ZZR600",
        "modelGroup": "ZZR600",
        "generation": null,
        "modelId": "ZZR600",
        "model": "ZZR600",
        "trim": null,
        "version": "ZZR600",
        "fuelId": "ESSENCESANSPLOMB",
        "fuel": "Essence sans plomb",
        "genericFuelId": 1,
        "genericFuel": "Essence",
        "transmissionTypeId": null,
        "transmissionType": null,
        "genericTransmissionTypeId": 1,
        "genericTransmissionType": "Boîte manuelle",
        "bodyId": "SOLO",
        "body": "SOLO",
        "genericBodyId": 10,
        "genericBody": "Coupé",
        "segmentationId": null,
        "segmentation": null,
        "driveTypeId": null,
        "driveType": "Chaîne",
        "genericDriveTypeId": null,
        "genericDriveType": null,
        "emissionId": null,
        "emission": null,
        "seats": 2,
        "gears": null,
        "doors": null,
        "valves": null,
        "torque": 6,
        "displacement": 600,
        "cylinders": null,
        "cylindersTypeId": null,
        "cylindersType": null,
        "horsepower": 100,
        "taxHorsepower": 6,
        "kilowatt": 0,
        "co2Emission": 0,
        "wltpCo2EmissionMin": null,
        "wltpCo2EmissionMax": null,
        "realCo2Emission": 180,
        "mixedConsumption": 7.5,
        "wltpMixedConsumptionMin": null,
        "wltpMixedConsumptionMax": null,
        "urbanConsumption": null,
        "wltpUrbanConsumptionMin": null,
        "wltpUrbanConsumptionMax": null,
        "extraUrbanConsumption": null,
        "wltpExtraUrbanConsumptionMin": null,
        "wltpExtraUrbanConsumptionMax": null,
        "length": null,
        "width": null,
        "height": null,
        "totalWeight": null,
        "payload": null,
        "wheelbase": null,
        "trailerLoadBraked": null,
        "trailerLoadUnbraked": null,
        "roofload": null,
        "energeticEfficiency": null,
        "curbWeight": 221,
        "realCurbWeight": null,
        "topSpeed": null,
        "acceleration": null,
        "trunkMinimumCapacity": null,
        "trunkMaximumCapacity": null,
        "modelCatalogBegin": "2020-01-01T01:00:00+01:00",
        "modelCatalogEnd": null,
        "catalogBeginPrice": null,
        "catalogEndPrice": null,
        "catalogExclVatPrice": null,
        "catalogInclVatPrice": null,
        "catalogTax": null,
        "catalogPriceOverloaded": false,
        "frontTyreWidth": null,
        "frontTyreHeight": null,
        "frontTyreSpeedIndex": null,
        "frontTyreDiameter": null,
        "rearTyreWidth": null,
        "rearTyreHeight": null,
        "rearTyreSpeedIndex": null,
        "rearTyreDiameter": null,
        "internalColorCode": null,
        "internalColorWording": null,
        "internalColorReference": null,
        "externalColorCode": null,
        "externalColorWording": "Rouge",
        "externalColorReference": "c10020",
        "putIntoService": "1996-05-10T02:00:00+02:00",
        "mileage": 38963,
        "mileageDate": "2024-03-01T11:39:39+01:00",
        "guaranteedMileage": false,
        "numberplate": "CK614DQ",
        "chassis": "ZX600E03970655555",
        "registration": null,
        "registrationNumber": null,
        "codeFactory": null,
        "recoverableVat": null,
        "tcenum": null,
        "cultureId": null,
        "referentialPicture": null,
        "picture": null,
        "damaged": false,
        "firstHand": false,
        "numberOfOwners": 3,
        "rolling": true,
        "upToDateMaintenanceBook": true,
        "purchaseSource": null,
        "origin": 1,
        "originValue": "Particulier",
        "import": false,
        "importCountryIso": null,
        "depositSale": false,
        "sellerBuyer": "Vincent SACHON",
        "forecastedMileage": 38963,
        "forecastedDate": null,
        "referenced": true,
        "stockEntrance": "2024-03-01T00:00:00+01:00",
        "internalNumber": "3",
        "automaticPriceUpdate": true,
        "isExported": false,
        "technicalControl": null,
        "nextTechnicalControl": null,
        "deliveryDate": null,
        "ordered": null,
        "warranty": "Garantie ICARE",
        "warrantyDuration": 3,
        "warrantyEnd": null,
        "assignment": null,
        "collaboratorAssignmentId": null,
        "reconciliationStatus": null,
        "price": 1690,
        "privateExclVatPrice": 1690,
        "privateInclVatPrice": 1690,
        "professionalExclVatPrice": null,
        "professionalInclVatPrice": null,
        "equipments": [
            {
                "id": 7,
                "wording": "Silencieux FRC 4 en 1 Carbone",
                "code": "FRCCARBZZR",
                "exclVatPrice": 390.83,
                "inclVatPrice": 469,
                "tax": 20,
                "referentialId": "18df9989f13",
                "serial": false,
                "pack": false,
                "custom": true,
                "packElements": [],
                "equipmentGroupings": [],
                "highlight": null,
                "updatedAt": "2024-03-01T11:39:00+01:00"
            },
            {
                "id": 6,
                "wording": "Bulle MRA TOURING Fumée",
                "code": "smokemrat",
                "exclVatPrice": 100,
                "inclVatPrice": 120,
                "tax": 20,
                "referentialId": "18df9980f9f",
                "serial": false,
                "pack": false,
                "custom": true,
                "packElements": [],
                "equipmentGroupings": [],
                "highlight": null,
                "updatedAt": "2024-03-01T11:39:00+01:00"
            },
            {
                "id": 5,
                "wording": "Tapis de réservoir bagster",
                "code": "bagsterred zzr",
                "exclVatPrice": 75,
                "inclVatPrice": 90,
                "tax": 20,
                "referentialId": "18df997affc",
                "serial": false,
                "pack": false,
                "custom": true,
                "packElements": [],
                "equipmentGroupings": [],
                "highlight": null,
                "updatedAt": "2024-03-01T11:39:00+01:00"
            }
        ],
        "pictures": [
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs94nTuXdlOfqulX7meDlCTUEa05gVFNE1yUjV7dJeapyu5Otg%3D%3D/KAWASAKI_ZZR600_PROFIL_DROIT.jpg",
                "templateReferenceId": 6
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs94nTuXdlOfqulX7meDlCTUEa05gVFNE1yUjV7dJeaoyu5Otg%3D%3D/KAWASAKI_ZZR600_34_AVANT_DROIT.jpg",
                "templateReferenceId": 7
            },
            {
                "pictureUrl": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDAqoBodQixUo7fs64m75Kg5J%2BDSgJUIPs94nTuXdlOfqulX7meDlCTUEa05gVFNE1yUjV7dJeegyu5Otg%3D%3D/KAWASAKI_ZZR600.jpg",
                "templateReferenceId": null
            }
        ],
        "paintings": [
            {
                "id": 16,
                "wording": "Peinture de série",
                "code": null,
                "exclVatPrice": 0,
                "inclVatPrice": 0,
                "tax": null,
                "referentialId": " ",
                "serial": true,
                "custom": false,
                "updatedAt": "2024-03-01T11:39:00+01:00"
            }
        ],
        "saddleries": [
            {
                "id": 15,
                "wording": "Sellerie de série",
                "code": null,
                "exclVatPrice": 0,
                "inclVatPrice": 0,
                "tax": null,
                "referentialId": " ",
                "leather": false,
                "serial": true,
                "custom": false,
                "updatedAt": "2024-03-01T11:39:00+01:00"
            }
        ],
        "serviceAgreements": [],
        "deliveryPack": {
            "id": 2,
            "wording": "PACK LIVRAISON BMW VO",
            "entityId": 414,
            "deleted": false,
            "elements": [
                {
                    "id": 17,
                    "wording": "Bidon huile 5W40 Advantec",
                    "exclVatPrice": 15,
                    "inclVatPrice": 18,
                    "tax": 20,
                    "updatedAt": "2024-02-27T17:52:29+01:00"
                },
                {
                    "id": 18,
                    "wording": "Carburant",
                    "exclVatPrice": 20.83,
                    "inclVatPrice": 25,
                    "tax": 20,
                    "updatedAt": "2024-02-27T17:52:29+01:00"
                },
                {
                    "id": 19,
                    "wording": "Gilet de sécurité",
                    "exclVatPrice": 12.5,
                    "inclVatPrice": 15,
                    "tax": 20,
                    "updatedAt": "2024-02-27T17:52:29+01:00"
                },
                {
                    "id": 20,
                    "wording": "Kit de bienvenue BMW",
                    "exclVatPrice": 33.33,
                    "inclVatPrice": 40,
                    "tax": 20,
                    "updatedAt": "2024-02-27T17:52:29+01:00"
                },
                {
                    "id": 21,
                    "wording": "Lubrifiant silicone SILKOLENE PRO PREP",
                    "exclVatPrice": 16.67,
                    "inclVatPrice": 20,
                    "tax": 20,
                    "updatedAt": "2024-02-27T17:52:29+01:00"
                }
            ],
            "updatedAt": "2024-02-27T17:52:29+01:00"
        },
        "accessories": [],
        "services": [],
        "status": {
            "id": "11",
            "code": "SAST",
            "wording": "Stock de vente"
        },
        "referentialPollutionClassification": null,
        "pollutionClassificationDesignation": "Crit'air",
        "pollutionClassificationValue": "5",
        "pollutionClassificationMedia": "https://filerender-api.openflex-preprod.eu/files/images/c3dGREFEbW93VjRWS2dVaL63nYj2qV75%2BDF0hVAUU28A_rvhsoG8_qg%2BeajJgoEfKJNmxmrXLBGE5uZX7zmamy7DBas1nRBSUwHMzhuaY7D3y%2BdMuB97CgMTUJ18NNw%3D",
        "comment": null,
        "eReserved": false,
        "updatedAt": "2024-04-22T10:28:17+02:00",
        "powertrainId": null,
        "powertrain": null,
        "numberOfBatteries": null,
        "batteryTypeId": null,
        "batteryType": null,
        "batteryCapacityAh": null,
        "batteryCapacityKwh": null,
        "homeBatteryChargingTime": null,
        "fastBatteryChargingTime": null,
        "hybridizationTypeId": null,
        "hybridizationType": null,
        "autonomy": null,
        "wltpAutonomyMin": null,
        "wltpAutonomyMax": null,
        "gasTypeId": null,
        "gasType": null,
        "electricConsumption": null,
        "wltpElectricConsumptionMin": null,
        "wltpElectricConsumptionMax": null,
        "gasTankCapacity": null,
        "gasTankCapacityUnit": null,
        "gasUrbanConsumption": null,
        "wltpGasUrbanConsumptionMin": null,
        "wltpGasUrbanConsumptionMax": null,
        "gasExtraUrbanConsumption": null,
        "wltpGasExtraUrbanConsumptionMin": null,
        "wltpGasExtraUrbanConsumptionMax": null,
        "gasMixedConsumption": null,
        "wltpGasMixedConsumptionMin": null,
        "wltpGasMixedConsumptionMax": null,
        "gasConsumptionUnit": null,
        "federalMotorTransportAuthorityNumber": null,
        "insurancePremiumIndex": null,
        "trailerHitch": null,
        "trailerHitchValue": null,
        "bonusPrice": null,
        "penaltyPrice": null,
        "equipmentsPrice": 679,
        "saddleriesPrice": 0,
        "paintingsPrice": 0,
        "serviceAgreementsPrice": 0,
        "damagesRepaired": false,
        "licences": [
            {
                "id": "1",
                "value": "A"
            }
        ],
        "familyId": "SPORTGT",
        "family": "Sport GT",
        "genericFamilyId": "9",
        "genericFamily": "Sport-GT",
        "wltpMixedConsumptionWithDischargedBatteryMin": null,
        "wltpMixedConsumptionWithDischargedBatteryMax": null,
        "wltpCo2EmissionWithDischargedBatteryMin": null,
        "wltpCo2EmissionWithDischargedBatteryMax": null,
        "wltpCo2EmissionClassMin": null,
        "wltpCo2EmissionClassMax": null,
        "wltpCo2ClassWithDischargedBatteryMin": null,
        "wltpCo2ClassWithDischargedBatteryMax": null
    }
}
EOD;

    // @TODO - Appel API pour récupérer le token
    function __construct() {
    }

    // Récupération de la liste des véhicules
    function getVehicles($max_lines = 0, $offset = 0, $params = []) {
        return json_decode(self::VEHICLES_EXAMPLE, true)['items'];
    }

    // @TODO - Faire appel API pour renvoyer nombre d'objets
    function countRows() {
        return 2;
    }

    // Fonctions pour les appels
    function sendRequest($url, $type = "POST") {

    }

    // Récupération des détail d'un véhicule
    function getVehicleDetails($vehicleId) {
        // Exemple moto
        return json_decode(self::MOTORBIKE_DETAILS_EXAMPLE, true)['car'];
        // Exemple voiture
        return json_decode(self::VEHICLE_DETAILS_EXAMPLE, true)['car'];
    }

}
?>